In [ ]:
#sample print
print('red')
print('###\n')

#print an arr
a = [12,'a',34.4]
for i in a:
    print(i)
print('###\n')

#print a matrix
a= [[0]*3 for _ in range(3)]
a[0][0]=3
print(a)
print('###\n')

print(2,3,4,sep="/",end=" abraca dabra")

red
###

12
a
34.4
###

[[3, 0, 0], [0, 0, 0], [0, 0, 0]]
###

2/3/4 abraca dabra

In [ ]:
a = b, c = 1, 2
print(a,b,c)

print(list(a))

(1, 2) 1 2
[1, 2]


In [ ]:
a = input('Enter string')
print('String is ',a,type(a))
b = int(input('Enter number'))
print('Number is ',b,type(b))
c = float(input('Enter decimal'))
print('Number is ',c,type(c))
d = complex(input('Enter complex'))
print('Number is ',d,type(d))

Enter string red


String is  red <class 'str'>


Enter number 12


Number is  12 <class 'int'>


Enter decimal 12


Number is  12.0 <class 'float'>


Enter complex 1+2j


Number is  (1+2j) <class 'complex'>


In [ ]:
a = 'Hello World'
print(a)
print(a*2)
print(a+' this append 🔥')
print(a[2::2])
print('[start, end, increment_by]')

Hello World
Hello WorldHello World
Hello World this append 🔥
loWrd
[start, end, increment_by]


In [ ]:
string = input('Enter a string to manipulate')
#traditional
res=''
for i in range(len(string)-1,-1,-1):
    res+=string[i]
print('Traditional method',res,end='\n\n')

#slicing
print('With slicing')
print(string[len(string):0:-1]+string[0])
print(string[::-1])

Enter a string to manipulate hello


Traditional method olleh

With slicing
olleh
olleh


In [ ]:
a = [1,2,3]
print('slicing works for list, tuple too')
a.append(4)
print(a[::-1])
b = (4,5,6)
print(b[3:0:-1])
c = {3:'red', 4:'blue'}
# c[5] = 'white'
c.update({5:'white'})
print('indexing not work for',type(c))
print(c)

slicing works for list, tuple too
[4, 3, 2, 1]
(6, 5)
indexing not work for <class 'dict'>
{3: 'red', 4: 'blue', 5: 'white'}


In [ ]:
b = (4,5,6)
print(b)
b = (1,2,3)
print(b)
b[0] = 0
print(b)

(4, 5, 6)
(1, 2, 3)


TypeError: 'tuple' object does not support item assignment

In [ ]:
c = {3:'red', 4:'blue'}
# c[5] = 'white'
c.update({5:'white'})
print('key  value')
for i in c:
    print(i, '  ', c[i])

key  value
3    red
4    blue
5    white


In [ ]:
a = [1, 2, 3, 4, 5]
print('Sum is',sum(a))
print('Length is',len(a))
print('Absolute of -34.5 : ',abs(-34.5))
print('Round of -34.1556 : ',round(-34.1556))
import math as m
print('log10(10)',m.log10(10))

Sum is 15
Length is 5
Absolute of -34.5 :  34.5
Round of -34.1556 :  -34
log10(10) 1.0


In [ ]:
def area(len, wid):
    return len*wid;

print(area(3,4))

12


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
# print(a+[5,2,3])
print(a[1,::-1])
print(a[:,0])

[6 5 4]
[1 4]


In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
print("Dimensions",a.ndim)
print("Size",a.size)
print("Shape",a.shape)
print("Average",np.mean(a))
print("Max of axis 1",np.max(a,axis=1))
print("Min of axis 0",np.min(a,axis=0))
print("Diagonal",a.diagonal())

Dimensions 2
Size 6
Shape (2, 3)
Average 3.5
Max of axis 1 [3 6]
Min of axis 0 [1 2 3]
Diagonal [1 5]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[1,2,3]])
print(np.add(a,b))
print(np.multiply(a,b))

[[ 8 10 12]
 [ 5  7  9]]
[[ 7 16 27]
 [ 4 10 18]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print("Flatten",a.flatten())
print("Transpose",a.T)
print("Reshape",a.reshape(6,1))

Flatten [1 2 3 4 5 6]
Transpose [[1 4]
 [2 5]
 [3 6]]
Reshape [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
